M48
; DRILL file {KiCad 9.0.7} date 2026-03-24T12:37:27-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-24T12:37:27-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.400
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.420
%
G90
G05
T1
X61.872Y-24.413
X89.176Y-24.413
T2
X36.515Y-24.413
X51.125Y-24.413
M30
