M48
; DRILL file {KiCad 8.0.4} date 2024-11-07T09:22:55-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-07T09:22:55-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0551
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0559
%
G90
G05
T1
X2.4359Y-0.9612
X3.5109Y-0.9612
T2
X1.4376Y-0.9612
X2.0128Y-0.9612
M30
